matrix:
  include:
    - language: python
      python: 3.5
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      before_script:
        - cd backend
      script:
        - python manager.py test
